---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-quotegen
spec:
  params:
    - name: url
      value: 'https://github.com/kirikae/demo-quote-gen.git'
    - name: revision
      value: sql
  type: git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  generation: 1
  name: image-backend
spec:
  params:
    - name: url
      value: 'image-registry.openshift-image-registry.svc:5000/quote-pipeline/backend'
  type: image
