---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: quotegen-v1
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'quotegen:v1'
  source:
    git:
      ref: master
      uri: 'https://github.com/kirikae/demo-quote-gen.git'
    contextDir: quotegen
    type: Git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'python:latest'
        namespace: openshift
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 1      
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: quotegen-v2
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'quotegen:v2'
  source:
    git:
      ref: master
      uri: 'https://github.com/kirikae/demo-quote-gen.git'
    contextDir: quotegen      
    type: Git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'python:latest'
        namespace: openshift  
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 1   
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
